// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/url": {
            "post": {
                "description": "Creates a new shortened URL, optionally with a customized code. Auto-generates a highly-secure Snowflake ID if no code is provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "URLs"
                ],
                "summary": "Create New Short URL",
                "parameters": [
                    {
                        "description": "URL Creation Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateUrlRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "URL Created Successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.CreateUrlResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid Input / Validation Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "409": {
                        "description": "URL Code Already Exists",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateUrlRequest": {
            "type": "object",
            "required": [
                "accountNumber",
                "state",
                "url"
            ],
            "properties": {
                "accountNumber": {
                    "type": "string",
                    "example": "93090290290"
                },
                "code": {
                    "type": "string",
                    "example": "john-doe"
                },
                "expiredAt": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "state": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "example": "john.doe@example.com"
                }
            }
        },
        "models.CreateUrlResponse": {
            "type": "object",
            "properties": {
                "accountNumber": {
                    "type": "string",
                    "example": "8989489484"
                },
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2026-01-24T15:57:37+07:00"
                },
                "expiredAt": {
                    "type": "string",
                    "example": "2026-01-24T15:57:37+07:00"
                },
                "metadata": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "example.com - shortened"
                },
                "state": {
                    "type": "string",
                    "example": "active"
                },
                "type": {
                    "type": "string",
                    "example": "url"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2026-01-24T15:57:37+07:00"
                },
                "url": {
                    "type": "string",
                    "example": "http://example.com"
                }
            }
        },
        "models.Metadata": {
            "type": "object",
            "properties": {
                "requestId": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "totalRows": {
                    "type": "integer"
                }
            }
        },
        "models.PaginationOutput": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next": {
                    "type": "string"
                },
                "prev": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "Request has been successfully processed."
                },
                "metadata": {
                    "$ref": "#/definitions/models.Metadata"
                },
                "pagination": {
                    "$ref": "#/definitions/models.PaginationOutput"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
