application:
  name: "go-link-generator"
  version: "1.0.0"
  port: 8080
  environment: "local"
  host: "0.0.0.0"
  timeout: 30
  timezone: "UTC"

authorization:
  issuer: ""
  api_key: ""

cors:
  headers_allowed:
    - "Authorization"
    - "Content-Type"
    - "X-API-Key"
    - "X-Request-ID"

postgresql:
  name: ""
  user: ""
  password: ""
  host: ""
  port: 5432
  ssl_mode: "disable"
  max_idle_conns: 5
  max_open_conns: 20
  conn_max_lifetime: "5m"

tracing:
  endpoint: ""
  service_name: ""

url:
  length: 1
  code_generation_retries: 1
  code_generation_backoff: 1
  secret: ""
  machine_id: 1
  secure_length: 1

kafka:
  brokers:
    - ""
  topics:
    link: ""
    link_dlq: "" 
  producer:
    required_acks: "all"
    retry:
      max: 1
      backoff: 250ms
    partitioner: "hash"
    max_message_bytes: 1
    timeout:
      dial: 10s
      read: 10s
      write: 10s
  consumer:
    group_id: ""
    initial_offset: ""
    retry:
      max: 1
      backoff: 1
    timeout:
      dial: 10s
      read: 10s
      write: 10s
      session: 10s
      rebalance: 60s
    heartbeat_interval: 3s